# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /

# add `/app/node_modules/.bin` to $PATH
ENV PATH /client/node_modules/.bin:$PATH

# install and cache app dependencies
COPY . ./

RUN yarn install && yarn add react-scripts -g

# start app
CMD ["yarn", "start"]

EXPOSE 3000